export const ERROR_CODES = {
  CHAIN: {
    UNSUPPORTED_CHAIN: "UNSUPPORTED_CHAIN",
    UNSUPPORTED_GAME: "UNSUPPORTED_GAME",
  },
  WAGMI: {
    ACCOUNT_MISSING: "ACCOUNT_MISSING",
    GET_TRANSACTION_RECEIPT_ERROR: "GET_TRANSACTION_RECEIPT_ERROR",
  },
  TRANSACTION: {
    TOKEN_APPROVAL_ERROR: "TOKEN_APPROVAL_ERROR",
    TOKEN_METADATA_ERROR: "TOKEN_METADATA_ERROR",
  },
  READ: {
    CHAINLINK_VRF_COST_ERROR: "CHAINLINK_VRF_COST_ERROR",
  },
  GAME: {
    PLACE_BET_ERROR: "PLACE_BET_ERROR",
    PLACE_BET_EVENT_NOT_FOUND: "PLACE_BET_EVENT_NOT_FOUND",
    ROLL_EVENT_ERROR: "ROLL_EVENT_ERROR",
    ROLL_EVENT_TIMEOUT: "ROLL_EVENT_TIMEOUT",
    GET_PAUSED_ERROR: "GET_PAUSED_ERROR",
    GET_TOKEN_ERROR: "GET_TOKEN_ERROR",
    GET_AFFILIATE_HOUSE_EDGE_ERROR: "GET_AFFILIATE_HOUSE_EDGE_ERROR",
  },
  BANK: {
    GET_TOKENS_ERROR: "GET_TOKENS_ERROR",
    GET_BET_REQUIREMENTS_ERROR: "GET_BET_REQUIREMENTS_ERROR",
  },

  WALLET: {},
} as const;
