export const ERROR_CODES = {
  CHAIN: {
    UNSUPPORTED_CHAIN: "UNSUPPORTED_CHAIN",
    GAME_NOT_AVAILABLE: "GAME_NOT_AVAILABLE",
  },
  WAGMI: {
    ACCOUNT_MISSING: "ACCOUNT_MISSING",
  },
  TRANSACTION: {
    TOKEN_APPROVAL_ERROR: "TOKEN_APPROVAL_ERROR",
  },
  READ: {
    CHAINLINK_VRF_COST_ERROR: "CHAINLINK_VRF_COST_ERROR",
  },
  GAME: {
    PLAY_GAME_ERROR: "PLAY_GAME_ERROR",
  },

  WALLET: {},
} as const;
